### ISSUE TITLE
Feature Request: Visible Collision Map for Debugging

### ISSUE THREAD

**Issue by RestartMV** [AltimitSystems/mv-plugins#43]
One thing that is frustrating to deal with when making a game is trying to figure out whether or not the collision map actually is correct, or if an inadvertent screw-up with the map maker put a hole somewhere.  

Testing maps by bumping against every wall to try to find hidden holes in the scenery (the current recommended method) is tedious, error-prone, and time-consuming.

Since altimit motion already knows exactly where all the collision meshes are, having a debug mode where it draws them onscreen (with a bright red line, or something) would be incredibly useful.

**Comment by felixjones** [comment]
This is already a feature: https://github.com/AltimitSystems/mv-plugins/tree/master/movement-debug
